apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-name
spec:
  accessModes:
    - ReadWriteOnce
  capa
  hostPath:
    path: /data/location

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-name
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
